### ISSUE TITLE
How to set host name?

### ISSUE THREAD

**Issue by rsoika** [microprofile-extensions/openapi-ext#30]
I am running the openapi-ext in Payara-micro on Docker.
This works fine, but the server box shows only the internal docker host name:

![image](https://user-images.githubusercontent.com/1339124/81421853-6e2cd880-9152-11ea-8ed0-8006a5c57c03.png)

How can I overwrite or add the external hostname (e.g. localhost)
I read that it is possible to configure swagger ui with the microprofile config api, but I did not found an example how the config parameter have to look like. 

I tried something like this in my docker-compose file:

```
  training-service:
    image: imixs/imixs-ml-training-service
    environment:
      OPENAPI-UI_COPYRIGHTBY: "Ralph"
```

But it did not work. Also I found no information how the server configuration variable should be named.
